COURSE_ACTS(COURSE_BOB, _(" 1 SUPER MOUNTAINS"),	_("! SWITCH BOXES"),	_("HOUSE TREASURE"),	_("COLLECT THE BLUE STARS"),	_("HIDDEN 8 RED COINS"),	_("WING CAP REQUIRED"),	_("CHAMPION'S CHALLENGE"))

COURSE_ACTS(COURSE_WF, _(" 2 SANDY CASTLE"),	_("KING WHOMP'S BATTLE"),	_("TRICKY SLOPES"),	_("SHELL RIDE FOR RED COINS"),	_("SECRET BEHIND THE WALL"),	_("ANOTHER SECRET WALL"),	_("INSIDE THE CAGE"))

COURSE_ACTS(COURSE_JRB, _(" 3 UNDERWATER CASTLE"),	_("EXPLORING THE CASTLE"),	_("FIVE SECRET COINS"),	_("SCARY METAL BLOCKS OF FAILURE"),	_("RED UNDERWATER TREASURE"),	_("IN THE QUICKSAND ROOM"),	_("THE STAR IN THE CORNER"))

COURSE_ACTS(COURSE_CCM, _(" 4 SNOWY MOUNTAINS"),	_("FINDING THE LOST PENGUIN"),	_("SHOOT TO THE MOUNTAIN"),	_("SECRET INSIDE THE MOUNTAIN"),	_("SNOWY RED COINS"),	_("5 SECRET SPOTS"),	_("TREASURE IN THE SKY"))

COURSE_ACTS(COURSE_BBH, _(" 5 GHOSTY HOUSE"),	_("BIG BOO ON THE ROOF"),	_("SECRET TUNNEL RIDE"),	_("JUMPING PARCOURS OF DOOM"),	_("8 RED COINS IN THE HOUSE"),	_("BOOKCASE CLIMBING"),	_("SOMEWHERE IN THE SKY"))

COURSE_ACTS(COURSE_HMC, _(" 6 JOURNEY TO SPACE"),	_("CLIMB THROUGH THE PLANET BUILDING"),	_("SUPER WALLKICK TIME"),	_("INSIDE THE LAVA BUILDING"),	_("RED COINS IN SPACE"),	_("GUARDED FIRE SECRETS"),	_("FLY TO THE HIGHEST BOX"))

COURSE_ACTS(COURSE_LLL, _(" 7 FIERY LAVA WORLD"),	_("BOIL THE BIG BULLY"),	_("INSIDE THE VOLCANO"),	_("HOT RED COINS"),	_("BEHIND THE CAGE"),	_("TRICKY SWITCH BOXES"),	_("5 HOT SECRET BOXES"))

COURSE_ACTS(COURSE_SSL, _(" 8 TRICKY SAND LAND"),	_("TRICKY PILLARS"),	_("OUTSIDE SHELL RIDING"),	_("MORE TRICKY PILLARS"),	_("SANDY RED COINS"),	_("TRICKY BOXES ON THE SAND"),	_("BEHIND THE VANISHING WALL"))

COURSE_ACTS(COURSE_DDD, _(" 9 FLOWERY GRASS LAND"),	_("KING BOB-OMB'S BATTLE"),	_("HIDDEN PLATFORMS"),	_("RED COIN HUNTING"),	_("SECRETS UNDER PLATFORMS"),	_("FLY TO THE HIGHEST MOUNTAIN"),	_("ON THE HOUSE ROOF"))

COURSE_ACTS(COURSE_SL, _("10 KOOPA'S BEACH"),	_("KOOPA'S RACE"),	_("INSIDE THE MAZE"),	_("KOOPA'S RED COINS"),	_("KOOPA'S SECRETS"),	_("SHOOT TO THE QUICKSAND ROOM"),	_("HIDDEN STAR"))

COURSE_ACTS(COURSE_WDW, _("11 SKY PLATFORMS"),	_("SECRET ISLAND"),	_("MOUNTAIN JUMPING"),	_("PAINFUL RED COINS"),	_("BOX PUZZLE"),	_("VANISH CAP RUN"),	_("HIDDEN STAR"))

COURSE_ACTS(COURSE_TTM, _("12 CRYSTAL PIPE LAND"),	_("EXPLORING THE LAND"),	_("HIDDEN CLIMBABLE BOXES"),	_("CLIMBING THE CRYSTALS"),	_("RED COINS IN THE PIPES"),	_("INSIDE THE PIPE"),	_("HIDDEN STAR"))

COURSE_ACTS(COURSE_THI, _("13 FLOATING SNOWY LEVEL"),	_("PIRANHA PLANT PANIC"),	_("IN THE COLD WATER ROOM"),	_("ICY RED COINS"),	_("INTO THE HOUSE"),	_("MOUNTAIN CLIMBER"),	_("HIDDEN STAR"))

COURSE_ACTS(COURSE_TTC, _("14 JOURNEY TO SPACE II"),	_("HOUSE IN THE SKY"),	_("BEHIND THE WALL"),	_("TRICKY TINY PILLARS"),	_("RED COINS IN SPACE"),	_("FIND THE MYSTERIOUS WARP"),	_("SECRET SLOPE TREASURE"))

COURSE_ACTS(COURSE_RR, _("15 TOXIC CAVE"),	_("EXPLORING THE CAVE"),	_("BOX PARCOURS RUSH"),	_("TOP OF THE CAVE"),	_("TOXIC RED COINS"),	_("STARS OF THE WATERMARK"),	_("HIDDEN STAR"))

SECRET_STAR(15, _("   BOWSER'S TRICKY CASTLE"))
SECRET_STAR(16, _("   BOWSER'S GREEN TOXIC CASTLE"))
SECRET_STAR(17, _("   BOWSER'S FINAL BATTLE"))
SECRET_STAR(18, _("   SLIDE LEVEL"))
SECRET_STAR(19, _("   METAL CAP SWITCH"))
SECRET_STAR(20, _("   WING CAP SWITCH"))
SECRET_STAR(21, _("   VANISH CAP SWITCH"))
SECRET_STAR(22, _("   SECOND OVERWORLD"))
SECRET_STAR(23, _("   FOURTH OVERWORLD"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   BONUS STARS"))
EXTRA_TEXT(0,_("YOU GOT A BONUS STAR!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
