COURSE_ACTS(COURSE_BOB, _(" 1 AUTUMNAL SCENERY"),	_("KING BOB-OMB IS BACK"),	_("IN THE LITTLE CAVE"),	_("THE TOWER ROCK"),	_("SMALL PLATFORMS"),	_("AUTUMNAL RED COINS"),	_("HIDDEN STAR"))

COURSE_ACTS(COURSE_WF, _(" 2 ICE ISLANDS"),	_("THE BULLY ON AN ISLAND"),	_("JUMP OVER THE ICE"),	_("ICY PILLARS"),	_("PLATFORMS ABOVE THE ICE"),	_("8 ICY RED COINS"),	_("ON THE ROOF OF THE TOWER"))

COURSE_ACTS(COURSE_JRB, _(" 3 DANGEROUS WATERS"),	_("PLATFORM PARCOURS"),	_("UNDERWATER ROOM"),	_("PILLAR JUMPING"),	_("OVER-WATER FLIGHT"),	_("TREASURE HUNT"),	_("WET RED COINS"))

COURSE_ACTS(COURSE_CCM, _(" 4 KING BOO'S NEW HOUSE"),	_("KING BOO RETURNS"),	_("NARROW PATH"),	_("FROM TOWER TO TOWER"),	_("8 GHOSTLY RED COINS"),	_("BLOCKS OF DEATH"),	_("HIDDEN STAR"))

COURSE_ACTS(COURSE_BBH, _(" 5 LAVA CITY"),	_("HIGH IN THE AIR"),	_("FLOATING PILLARS"),	_("THE HIGH TOWER"),	_("GLOWING RED COINS"),	_("THE FIRE RINGS"),	_("HIDDEN STAR"))

COURSE_ACTS(COURSE_HMC, _(" 6 FIREPROOF WOOD"),	_("THE BIG WOOD SCAFFOLD"),	_("TRICKY WOODEN LOGS"),	_("THE METAL BOXES"),	_("FIND THE 8 RED COINS"),	_("WOOD BLOCKS"),	_("HIDDEN STAR"))

COURSE_ACTS(COURSE_LLL, _(" 7 QUICKSAND HAZARDS"),	_("THE QUICKSAND TOWER"),	_("THE QUICKSAND MAZE"),	_("8 SANDY RED COINS"),	_("RISKY JUMPS"),	_("THE THWOMP ISLAND"),	_("HIDDEN IN THE DESERT"))

COURSE_ACTS(COURSE_SSL, _(" 8 STALAGMITE CLIFF"),	_("WOODEN JUMPS"),	_("CLIFF CAVE"),	_("JUMPMAN"),	_("CLIFF MAZE"),	_("THE RED COINS AT THE CLIFF"),	_("HIDDEN STAR"))

COURSE_ACTS(COURSE_DDD, _(" 9 CRYSTAL CAVERN"),	_("AN UNEXPECTED VISITOR"),	_("WALL PATH"),	_("ANGRY THWOMPS"),	_("MYSTERIOUS PLATFORMS"),	_("THE GOLDEN CAVE"),	_("RED CRYSTAL COINS"))

COURSE_ACTS(COURSE_SL, _("10 MARIO'S SPACE JOURNEY"),	_("THE SPACE WINDMILL"),	_("THE RESEARCH FACILITY"),	_("THE SAND PLATEAU"),	_("THE MYSTERIOUS ROCK"),	_("RED COINS OF THE SPACE"),	_("HIDDEN STAR"))

COURSE_ACTS(COURSE_WDW, _("11 GHOST CITY"),	_("SHOCKING ARROW LIFTS!"),	_("TOP O' THE TOWN"),	_("SECRETS IN THE SHALLOWS & SKY"),	_("EXPRESS ELEVATOR--HURRY UP!"),	_("GO TO TOWN FOR RED COINS"),	_("QUICK RACE THROUGH DOWNTOWN!"))

COURSE_ACTS(COURSE_TTM, _("12 AQUATIC TEMPLE"),	_("SCALE THE MOUNTAIN"),	_("MYSTERY OF THE MONKEY CAGE"),	_("SCARY 'SHROOMS, RED COINS"),	_("MYSTERIOUS MOUNTAINSIDE"),	_("BREATHTAKING VIEW FROM BRIDGE"),	_("BLAST TO THE LONELY MUSHROOM"))

COURSE_ACTS(COURSE_THI, _("13 FLOATING METAL SHIP"),	_("PLUCK THE PIRANHA FLOWER"),	_("THE TIP TOP OF THE HUGE ISLAND"),	_("REMATCH WITH KOOPA THE QUICK"),	_("FIVE ITTY BITTY SECRETS"),	_("WIGGLER'S RED COINS"),	_("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14 TOXIC PLATEAUS"),	_("ROLL INTO THE CAGE"),	_("THE PIT AND THE PENDULUMS"),	_("GET A HAND"),	_("STOMP ON THE THWOMP"),	_("TIMED JUMPS ON MOVING BARS"),	_("STOP TIME FOR RED COINS"))

COURSE_ACTS(COURSE_RR, _("15 TIMELESS FORTRESS"),	_("CRUISER CROSSING THE RAINBOW"),	_("THE BIG HOUSE IN THE SKY"),	_("COINS AMASSED IN A MAZE"),	_("SWINGIN' IN THE BREEZE"),	_("TRICKY TRIANGLES!"),	_("SOMEWHERE OVER THE RAINBOW"))

SECRET_STAR(15, _("   BOWSER IN THE DRAB WORLD"))
SECRET_STAR(16, _("   BOWSER'S SAND TEMPLE"))
SECRET_STAR(17, _("   BOWSER'S TOWER OF EVIL"))
SECRET_STAR(18, _("   SECRET GOOMBA FOREST"))
SECRET_STAR(19, _("   THE METAL CAP CAVE"))
SECRET_STAR(20, _("   TOWERS OF THE WING CAP"))
SECRET_STAR(21, _("   THE LOST VANISH CAP"))
SECRET_STAR(22, _("   NIGHTSKY FORTRESS"))
SECRET_STAR(23, _("   "))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   BONUS STARS"))
EXTRA_TEXT(0,_("A BONUS STAR!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
